export const FIELDS = [
  "id^3",
  "label.*^3",
  "title_abs_text^3",
  "acronym.*^3",
  "description.*^2",
  "domains.label.*",
  "call.id",
  "call.label",
  "action.id",
  "action.label.*",
  "keywords.*",

  "publications.id",
  "publications.title.*",
  "publications.authors.fullName",
  "publications.authors.person",
  "publications.domains.label.*",
  "publications.domains.code",

  "participants.structure.label.*",
  "participants.structure.acronym.*",
  "participants.label.*",
  "participants_id_search",
  "participants.structure.institutions.label.*",
]
export const LIGHT_SOURCE = [
  "label.*",
  "publications",
  "participants.label",
  "participants.structure.id",
  "participants.structure.label.*",
  "participants.structure.mainAddress.*",
  "year",
  "type",
  "id",
  "keywords.*",
];
